version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          command: |
           export DEBIAN_FRONTEND=noninteractive
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd ccache openjdk-8-jdk python python2 python3 cpio python3-pip tzdata
           ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
           git clone https://github.com/Neternels/SURYA_kernel.git -b StromBreaker_main  --depth=1 msm
           cd msm
           source kramel.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
