version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
         env: TZ=Asia/Dubai
          command: |
           ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd ccache python3 python-is-python3 openjdk-8-jdk 
           java -version
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
